### ISSUE TITLE
Apk server implement? 

### ISSUE THREAD

**Issue by hapishyguy** [Kruceo/KruceoLauncher#1]
What does apk server implement mean?

**Comment by Kruceo** [comment]
> What does apk server implement mean? 

You can setup a server that will control the installed apps in launcher, like apps that you want (or no) in the device, the server will provide the apps that you want to install, see the branch "server"

**Comment by hapishyguy** [comment]
Where is the branch. "server". I dont see it.

**Comment by hapishyguy** [comment]
I got the branch part. Thanks!
